#!/bin/bash
### BEGIN INIT INFO
# Provides:          bsext-pydev
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: BrightSign Python Development Extension
# Description:       Install python3.8 and common python packages for BrightSign development.
### END INIT INFO

# Source function library if it exists
[ -f /etc/init.d/functions ] && . /etc/init.d/functions

SCRIPT_PATH=$(dirname $(realpath $0))
DAEMON_NAME="bsext-pydev"
PIDFILE="/var/run/${DAEMON_NAME}.pid"

# defaults -- these can be overridden by the registry
DISABLE_AUTO_START=false

# Common function to run the attention demo
run() { }
    # Default to running in foreground
    local background=$1
    
    # if [ "$background" = "true" ]; then
    #     # Run as a daemon in the background
    #     start-stop-daemon --start --background --make-pidfile --pidfile ${PIDFILE} \
    #                       --exec ${SOC_HOME}/yolo_demo -- ${CMD_ARGS}
    # else
    #     # Run directly in foreground
    #     ${SOC_HOME}/yolo_demo ${CMD_ARGS}
    # fi
}

do_start() {
    # check registry for auto-start
    reg_disable_auto_start=$(registry extension ${DAEMON_NAME}-disable-auto-start)
    if [ -n "${reg_disable_auto_start}" ]; then
        DISABLE_AUTO_START=${reg_disable_auto_start}
    fi

    if [[ "${DISABLE_AUTO_START,,}" =~ ^(true|yes|1)$ ]]; then
        echo "Auto-start is disabled for ${DAEMON_NAME}"
        return
    fi

    # Start the attention_demo process as a daemon
    run_yolo_demo true
}

do_stop() {
    start-stop-daemon --stop --pidfile ${PIDFILE}
    rm -f ${PIDFILE}
}

case "$1" in
    start)
        echo "Starting ${DAEMON_NAME}"
        do_start
        ;;
    stop)
        echo "Stopping ${DAEMON_NAME}"
        do_stop
        ;;
    restart)
        echo "Restarting ${DAEMON_NAME}"
        do_stop
        do_start
        ;;
    run)
        echo "Running ${DAEMON_NAME} in foreground"
        # Run directly in foreground (not as daemon)
        run_yolo_demo false
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|run}"
        exit 1
        ;;
esac

exit 0
